### ISSUE TITLE
GET /weather sends string rather than JSON

### ISSUE THREAD

**Issue by mmerkes** [ionic-in-action/apis#1]
When you GET /weather, the server sends a string as a response, which the browser and Angular don't know to parse it. The issue is that request returns a string as the body (not a JS object in this case), which is passed into res.json and that's expecting a JS object. body either needs to be parsed first (by request or manually), or using res.send seems to work.

**Comment by gnomeontherun** [comment]
Yup, the reason I had to make this service in the first place was that the weather service was down. I'm pushing up a fix for this, thanks for the report!

**Comment by gnomeontherun** [comment]
API returns JSON correctly now.

https://ionic-in-action-api.herokuapp.com/weather

**Comment by mmerkes** [comment]
Excellent. Works as expected now.
